import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="flex flex-1 flex-col gap-8 items-center justify-start w-full">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">SignupScreen</Link>
        </li>
        <li>
          <Link to="/messages">BuddyDashboard</Link>
        </li>
        <li>
          <Link to="/buddydashboardone">BuddyDashboardOne</Link>
        </li>
        <li>
          <Link to="/signupscreenone">SignupScreenOne</Link>
        </li>
        <li>
          <Link to="/signupscreenactive">SignupScreenactive</Link>
        </li>
        <li>
          <Link to="/signedup">Signedup</Link>
        </li>
        <li>
          <Link to="/verifyemail">Verifyemail</Link>
        </li>
        <li>
          <Link to="/verifyemailone">VerifyemailOne</Link>
        </li>
        <li>
          <Link to="/loginscreen">LoginScreen</Link>
        </li>
        <li>
          <Link to="/loginscreenactive">LoginScreenactive</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
